prometheus-exporter:
    run-as-user: root
    path: /opt/srlinux/usr/bin/
    launch-command: ./srl-prometheus-exporter
    search-command: ./srl-prometheus-exporter
    version-command: echo "GIT_TAG"
    wait-for-config: Yes
    failure-threshold: 10
    yang-modules:
        names: 
            - "prometheus-exporter"
        source-directories:
            - "/opt/prometheus-exporter/yang/"
            - "/opt/srlinux/models/srl_nokia/models/common"
            - "/opt/srlinux/models/srl_nokia/models/network-instance"
            - "/opt/srlinux/models/srl_nokia/models/system"
